layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
     - phillipschmidt88.github.io

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  hackerrank: phillips23
  # instagram: your_username
  # keybase: your_username
  linkedin: phillipschmidtroboticist
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Robotics
    web_url: http://paulfurgale.info/news/2014/6/9/representing-robot-pose-the-good-the-bad-and-the-ugly
    image_url: http://wiki.ros.org/navigation?action=AttachFile&do=get&target=nav_comic.png
    
  - name: Computer Vision
    web_url: https://www.robots.ox.ac.uk/~vgg/hzbook/
    image_url: https://upload.wikimedia.org/wikipedia/en/7/7d/Lenna_%28test_image%29.png
    
  - name: Control Engineering
    web_url: https://www.tandfonline.com/doi/abs/10.1080/00207179208934253?journalCode=tcon20
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Ideal_feedback_model.svg/680px-Ideal_feedback_model.svg.png
